# Generated by Django 3.1 on 2020-11-23 11:37

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20201123_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, unique=True, upload_to=blog.models.upload_to)),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(blank=True)),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('data_last_child', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Папка', 'Папка'), ('Файл', 'Файл')], max_length=30)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
