# Generated by Django 3.1.4 on 2020-12-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.JSONField(blank=True),
        ),
    ]
