# Generated by Django 3.1.4 on 2021-01-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201231_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
    ]
