# Generated by Django 3.1.4 on 2021-01-02 16:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210101_2245'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('pricedir', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
