# Generated by Django 3.1.4 on 2021-01-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210102_1904'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='pricedir',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
