# Generated by Django 3.1 on 2020-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='minitag',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
