# Generated by Django 3.1.4 on 2020-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201123_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='settings',
            field=models.JSONField(),
        ),
    ]
