# Generated by Django 3.1.4 on 2020-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201231_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='settings',
            field=models.JSONField(blank=True),
        ),
    ]
