# Generated by Django 3.1.4 on 2021-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201231_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to='user.role'),
        ),
    ]
