# Generated by Django 3.1.4 on 2021-01-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210104_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minitag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
