# Generated by Django 3.1.4 on 2021-01-04 14:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210104_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to),
        ),
    ]
